version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  catchup_live:
    build: .
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      CATCHUP_BLOCKS_LIVE_ENABLED: true

  catchup_old:
    build: .
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      CATCHUP_BLOCKS_CATCH_UP_ENABLED: true
