spring:
  application:
    name: catchup
  main:
    banner-mode: off

cloud:
  yandex:
    region: ru-central1
  aws:
    sqs:
      endpoint: https://message-queue.api.cloud.yandex.net/
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

logging:
  level:
    money.tegro: DEBUG

catchup.blocks:
  startseqno: 26205420

lite.client:
  ip: -1182143975
  port: 36573
  key: "ZYe6sDZZc63sH3JnpIS8Yj86NFGnRlQF9NOvzl6UM0c="
