name: Docker Image

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
      -
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build image with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage --imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
