name: Docker Image

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
      -

env:
  REGISTRY: ghcr.io
  IMAGE: tegroton/catchup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build image with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage --imageName=${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.ref_name }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.ref_name }}

      - name: Publish container image (latest)
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.ref_name }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
